### ISSUE TITLE
CBS-1 Сварить пельмени 

### ISSUE THREAD

**Issue by etonealbert** [EdwardPaul/crypto_backtest_system#3]
Пельмени во "зимнем пруду" — это оригинальное блюдо, которое можно приготовить для развлечения гостей или создания волшебной атмосферы в холодную зимнюю ночь. Вот рецепт необычных пельменей "во зимнем пруду":

Ингредиенты:

Для теста:
- 2 чашки муки
- 1 яйцо
- 1/2 чашки воды
- 1/2 чашки сливочного масла
- 1/2 чайной ложки соли

Для начинки:
- 300 г мелкой рыбы (например, треска или лосось)
- 1/2 луковицы, мелко нарезанной
- 2 столовые ложки сливочного масла
- Соль и перец по вкусу

Для "зимнего пруда":
- Крупные кубики льда
- Плоская миска или поднос

Инструкции:

1. Подготовьте тесто. В глубокой миске смешайте муку и соль. Добавьте яйцо, воду и масло. Замесите тесто и выложите его на рабочую поверхность, посыпанную мукой. Вымешивайте тесто в течение 5-7 минут до тех пор, пока оно не станет гладким и упругим. Заверните тесто в пленку и оставьте отдохнуть при комнатной температуре в течение 30 минут.

2. Подготовьте начинку. Рыбу измельчите и обжарьте в сковороде с сливочным маслом до готовности. Добавьте мелко нарезанный лук, посолите и поперчите по вкусу. Продолжайте готовить, пока лук не станет мягким и золотистым. Дайте начинке остыть.

3. Разделите тесто на небольшие кусочки и раскатайте их в тонкие круги, используя дополнительную муку, чтобы предотвратить прилипание. 

4. Положите небольшое количество начинки на каждый круг теста. Затем аккуратно сформируйте пельмени, складывая тесто пополам и уплотняя его по краям.

5. Для приготовления "зимнего пруда" выложите кубики льда на плоскую миску или поднос, создавая "ледяную поверхность".

6. Поставьте кастрюлю с водой на огонь и доведите ее до кипения. Когда вода закипит, аккуратно опустите пельмени в кипящую воду и варите их до тех пор, пока они не всплывут на поверхность. Затем дайте им вариться еще 2-3 минуты.

7. С помощью ложки с дырками аккуратно выньте пельмени из кипящей воды и переложите их на "зимний пруд" (на ледяную поверхность). Пельмени будут быстро остывать и образуют впечатление, будто они лежат на льду.

8. Подавайте пельмени "во зимнем пруду" горячими, приправленными соусом на ваш вкус. Например, можно использовать сливочный соус с зеленью или лимонным соусом.

Такие пельмени точно удивят ваших гостей и создадут необычную атмосферу на вашем столе!

**Comment by EdwardPaul** [comment]
Approved & merged
